package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Tuesday, 12 May, 2026 11:25:03 PM IST
*/

public interface CalculatorOperations 
{
  double add (double a, double b);
  double subtract (double a, double b);
  double multiply (double a, double b);
  double divide (double a, double b);
} // interface CalculatorOperations
